on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "data/**"
      - "po/**"
      - "subprojects/**"
      - "**/*.rs"
      - "src/**"
      - "Cargo.*"
      - "build-aux/**"
      - "meson*.*"
  pull_request:
    paths:
      - "data/**"
      - "po/**"
      - "subprojects/**"
      - "**/*.rs"
      - "src/**"
      - "Cargo.*"
      - "build-aux/**"
      - "meson*.*"

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: packet.flatpak
          manifest-path: build-aux/io.github.nozwock.Packet.Devel.json
          run-tests: true
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          verbose: true

  vendored-release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Vendored Release
    runs-on: ubuntu-latest
    needs: [flatpak]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cargo-vendor-filterer
        run: cargo install cargo-vendor-filterer
      - name: Create vendored sources
        run: build-aux/dist-vendor.sh ../ src
        shell: bash
      - name: Archive repository
        run: git archive --format tar HEAD > packet-${{ github.ref_name }}.tar
      - name: Add vendored sources and cargo config to tarball
        run: tar -rf packet-${{ github.ref_name }}.tar .cargo vendor
      - name: Compress tarball
        run: xz -z packet-${{ github.ref_name }}.tar
      - name: Generate checksum
        run: sha256sum packet-${{ github.ref_name }}.tar.xz > packet-${{ github.ref_name }}.tar.xz.sha256sum
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Extract release notes
        run: |
          echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
          xmllint --xpath '//release[1]/description' data/io.github.nozwock.Packet.metainfo.xml.in.in | xmllint --format - >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ env.RELEASE_NOTES }}
          prerelease: ${{ contains(github.ref, 'beta') }}
          files: |
            packet-${{ github.ref_name }}.tar.xz
            packet-${{ github.ref_name }}.tar.xz.sha256sum
